name: Python release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish distributions

    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    env:
      GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}

    outputs:
      artifact_id: ${{ steps.publish.outputs.artifact-id }}
      artifact_url: ${{ steps.publish.outputs.artifact-url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Package and publish
        uses: GlobalScope-HUN/python-package-action@v1
        with:
          debian-dist-type: 'library'

  release:
    name: Create Release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    needs: [ publish ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: context-logger
          path: ${{ github.workspace }}/context-logger
      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/context-logger
      - name: Tag latest
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          git tag -fa ${VERSION_TAG} -m "Release ${VERSION_TAG}"
          git push origin :refs/tags/${VERSION_TAG}
          
          git tag -fa latest -m "Latest release"
          git push origin :refs/tags/latest
          
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release version tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/context-logger/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release latest tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            ${{ github.workspace }}/context-logger/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
